/********* User Preferences *********/

#define MAX_CONNECTED_SERVERS	3
#define MAX_PARALLEL_REQUESTS	20
#define SD_CARD_CHIP_SELECT		15
#define MAX_TRANSACTION_COUNT	10
#define MAX_TRANSACTION_SIZE	1000
#define REMOVE_CONFIRMED_TRANSACTION_AFTER	12
#define REMOVE_UNCONFIRMED_TRANSACTION_AFTER	12
#define MAX_TRACKED_ADDRESSES_COUNT	5
#define USE_TEST_NET
// #define USE_MAIN_NET
// #define ENABLE_DEBUG_MESSAGES